In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
mat1=np.array([1,2,3,4,5])
mat2=np.array([[1,2],[2,1]])
mat3=np.array([[[4,3,2],[5,7,8],[2,6,1]]])
mat4=np.array([[[[1,0,1],[0,1,1],[1,1,0]]]])
mat5=np.array([[[[[1,2,3],[4,4,6],[7,8,9]]]]])

In [3]:
from numpy import linalg as la

In [4]:
#DETERMINANT
#det for 1-d matrix is not possible
print(la.det(mat2))
print(la.det(mat3))
print(la.det(mat4))
print(la.det(mat5))

-2.9999999999999996
[-99.]
[[-2.]]
[[[12.]]]


In [5]:
#INVERSE
#inverse for 1-d matrix is not possible
print(la.inv(mat2))
print(la.inv(mat3))
print(la.inv(mat4))
print(la.inv(mat5))

[[-0.33333333  0.66666667]
 [ 0.66666667 -0.33333333]]
[[[ 4.14141414e-01 -9.09090909e-02 -1.01010101e-01]
  [-1.11111111e-01  5.20417043e-17  2.22222222e-01]
  [-1.61616162e-01  1.81818182e-01 -1.31313131e-01]]]
[[[[ 0.5 -0.5  0.5]
   [-0.5  0.5  0.5]
   [ 0.5  0.5 -0.5]]]]
[[[[[-1.00000000e+00  5.00000000e-01  1.26882631e-16]
    [ 5.00000000e-01 -1.00000000e+00  5.00000000e-01]
    [ 3.33333333e-01  5.00000000e-01 -3.33333333e-01]]]]]


In [10]:
#RANK
print(la.matrix_rank(mat1))
print(la.matrix_rank(mat2))
print(la.matrix_rank(mat3))
print(la.matrix_rank(mat4))
print(la.matrix_rank(mat5))

1
2
[3]
[[3]]
[[[3]]]


In [15]:
#DIAGONAL
#rank is possible for only 1-d and 2-d
print(np.diag(mat1))
print(np.diag(mat2))

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
[1 1]


In [30]:
#TRACE
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.trace(mat))
print(np.trace(mat2))
print(np.trace(mat3))
print(np.trace(mat4))
print(np.trace(mat5))

15
2
[4 3 2]
[[1 0 1]
 [0 1 1]
 [1 1 0]]
[[[1 2 3]
  [4 4 6]
  [7 8 9]]]


EIGEN VECTORS AND VALUES

In [33]:
x,y=la.eig(mat2)
print("roots:",x)
print("vectors:",y)
print(la.eigvals(mat2))

roots: [ 3. -1.]
vectors: [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[ 3. -1.]


In [34]:
x,y=la.eig(mat3)
print("roots:",x)
print("vectors:",y)
print(la.eigvals(mat3))

roots: [[13.528762    2.04667237 -3.57543437]]
vectors: [[[ 0.35272458  0.87634091  0.03452897]
  [ 0.82076382 -0.34986998 -0.61326967]
  [ 0.44936859 -0.33108549  0.78911854]]]
[[13.528762    2.04667237 -3.57543437]]


In [35]:
x,y=la.eig(mat4)
print("roots:",x)
print("vectors:",y)
print(la.eigvals(mat4))

roots: [[[-1.  1.  2.]]]
vectors: [[[[ 4.08248290e-01 -7.07106781e-01 -5.77350269e-01]
   [ 4.08248290e-01  7.07106781e-01 -5.77350269e-01]
   [-8.16496581e-01 -1.19365036e-17 -5.77350269e-01]]]]
[[[-1.  1.  2.]]]


In [36]:
x,y=la.eig(mat5)
print("roots:",x)
print("vectors:",y)
print(la.eigvals(mat5))

roots: [[[[15.81808513 -1.16929832 -0.64878681]]]]
vectors: [[[[[-0.23619902 -0.72109112  0.67391843]
    [-0.50226248 -0.20880816 -0.72963579]
    [-0.83183077  0.66062602  0.11604125]]]]]
[[[[15.81808513 -1.16929832 -0.64878681]]]]


#Dataset 1

In [10]:
df=pd.read_csv(r"C:\Users\SCET\Downloads\1_2015.csv")
df=df.drop(["Country","Region"],axis=1)

In [16]:
print(df.mean())

Happiness Rank                   79.493671
Happiness Score                   5.375734
Standard Error                    0.047885
Economy (GDP per Capita)          0.846137
Family                            0.991046
Health (Life Expectancy)          0.630259
Freedom                           0.428615
Trust (Government Corruption)     0.143422
Generosity                        0.237296
Dystopia Residual                 2.098977
dtype: float64


In [13]:
print(df.mode())

     Happiness Rank  Happiness Score  Standard Error  \
0              82.0            5.192         0.03751   
1               NaN              NaN         0.03780   
2               NaN              NaN         0.04394   
3               NaN              NaN         0.04934   
4               NaN              NaN         0.05051   
..              ...              ...             ...   
153             NaN              NaN             NaN   
154             NaN              NaN             NaN   
155             NaN              NaN             NaN   
156             NaN              NaN             NaN   
157             NaN              NaN             NaN   

     Economy (GDP per Capita)   Family  Health (Life Expectancy)  Freedom  \
0                     0.00000  0.00000                   0.92356  0.00000   
1                     0.01530  0.13995                       NaN  0.07699   
2                     0.01604  0.30285                       NaN  0.09245   
3                  

In [14]:
print(df.median())

Happiness Rank                   79.500000
Happiness Score                   5.232500
Standard Error                    0.043940
Economy (GDP per Capita)          0.910245
Family                            1.029510
Health (Life Expectancy)          0.696705
Freedom                           0.435515
Trust (Government Corruption)     0.107220
Generosity                        0.216130
Dystopia Residual                 2.095415
dtype: float64


In [18]:
print(df.describe())

       Happiness Rank  Happiness Score  Standard Error  \
count      158.000000       158.000000      158.000000   
mean        79.493671         5.375734        0.047885   
std         45.754363         1.145010        0.017146   
min          1.000000         2.839000        0.018480   
25%         40.250000         4.526000        0.037268   
50%         79.500000         5.232500        0.043940   
75%        118.750000         6.243750        0.052300   
max        158.000000         7.587000        0.136930   

       Economy (GDP per Capita)      Family  Health (Life Expectancy)  \
count                158.000000  158.000000                158.000000   
mean                   0.846137    0.991046                  0.630259   
std                    0.403121    0.272369                  0.247078   
min                    0.000000    0.000000                  0.000000   
25%                    0.545808    0.856823                  0.439185   
50%                    0.910245    1.02

In [19]:
print(df.sum())

Happiness Rank                   12560.00000
Happiness Score                    849.36600
Standard Error                       7.56579
Economy (GDP per Capita)           133.68968
Family                             156.58526
Health (Life Expectancy)            99.58098
Freedom                             67.72116
Trust (Government Corruption)       22.66065
Generosity                          37.49269
Dystopia Residual                  331.63833
dtype: float64


In [21]:
print(df.cumsum())

     Happiness Rank  Happiness Score  Standard Error  \
0                 1            7.587         0.03411   
1                 3           15.148         0.08295   
2                 6           22.675         0.11623   
3                10           30.197         0.15503   
4                15           37.624         0.19056   
..              ...              ...             ...   
153           11934          837.276         7.32523   
154           12089          840.616         7.36179   
155           12245          843.622         7.41194   
156           12402          846.527         7.49852   
157           12560          849.366         7.56579   

     Economy (GDP per Capita)     Family  Health (Life Expectancy)   Freedom  \
0                     1.39651    1.34951                   0.94143   0.66557   
1                     2.69883    2.75174                   1.88927   1.29434   
2                     4.02431    4.11232                   2.76391   1.94372   
3      

In [22]:
print(df.min())

Happiness Rank                   1.00000
Happiness Score                  2.83900
Standard Error                   0.01848
Economy (GDP per Capita)         0.00000
Family                           0.00000
Health (Life Expectancy)         0.00000
Freedom                          0.00000
Trust (Government Corruption)    0.00000
Generosity                       0.00000
Dystopia Residual                0.32858
dtype: float64


In [23]:
print(df.max())

Happiness Rank                   158.00000
Happiness Score                    7.58700
Standard Error                     0.13693
Economy (GDP per Capita)           1.69042
Family                             1.40223
Health (Life Expectancy)           1.02525
Freedom                            0.66973
Trust (Government Corruption)      0.55191
Generosity                         0.79588
Dystopia Residual                  3.60214
dtype: float64


In [24]:
print(df.count())

Happiness Rank                   158
Happiness Score                  158
Standard Error                   158
Economy (GDP per Capita)         158
Family                           158
Health (Life Expectancy)         158
Freedom                          158
Trust (Government Corruption)    158
Generosity                       158
Dystopia Residual                158
dtype: int64


In [25]:
from numpy import cov
covariance=cov(df)
print(covariance)

[[   4.88841846    4.83879729    4.70142994 ...   -8.94067707
    -8.82138793   -8.98078038]
 [   4.83879729    4.90609656    4.85312686 ...    6.65446601
     6.91187931    6.84394034]
 [   4.70142994    4.85312686    4.92188806 ...   22.31438288
    22.641738     22.68516687]
 ...
 [  -8.94067707    6.65446601   22.31438288 ... 2413.35472621
  2429.10053333 2444.88038009]
 [  -8.82138793    6.91187931   22.641738   ... 2429.10053333
  2445.28647938 2461.11016749]
 [  -8.98078038    6.84394034   22.68516687 ... 2444.88038009
  2461.11016749 2477.06518276]]


In [27]:
from scipy.stats import pearsonr#it works well for linear relationship/regression
corr,_=pearsonr(df['Happiness Rank'],df['Health (Life Expectancy)'])
print(corr)

-0.735612958442803


#Dataset 2

In [28]:
df=pd.read_csv(r"C:\Users\SCET\Downloads\3_Fitness.csv")

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   SALESMAN     11 non-null     object 
 1   JAN          11 non-null     float64
 2   FEB          11 non-null     float64
 3   MAR          11 non-null     float64
 4   APR          11 non-null     float64
 5   MAY          11 non-null     float64
 6   JUN          11 non-null     float64
 7   TOTAL SALES  11 non-null     float64
 8   Unnamed: 8   1 non-null      float64
 9   Unnamed: 9   0 non-null      float64
 10  Unnamed: 10  0 non-null      float64
 11  Unnamed: 11  6 non-null      object 
dtypes: float64(10), object(2)
memory usage: 1.3+ KB


In [30]:
df=df.drop(["SALESMAN","Unnamed: 8","Unnamed: 9","Unnamed: 10","Unnamed: 11"],axis=1)

In [31]:
print(df.mean())

JAN            101.090909
FEB             98.909091
MAR             94.909091
APR            103.818182
MAY             96.727273
JUN             85.090909
TOTAL SALES    579.818182
dtype: float64


In [32]:
print(df.mode())

     JAN   FEB   MAR   APR   MAY   JUN  TOTAL SALES
0   35.0  35.0  49.0  45.0  35.0  25.0        210.0
1    NaN   NaN   NaN   NaN  56.0  30.0        220.0
2    NaN   NaN   NaN   NaN   NaN  55.0        247.0
3    NaN   NaN   NaN   NaN   NaN  73.0        258.0
4    NaN   NaN   NaN   NaN   NaN   NaN        319.0
5    NaN   NaN   NaN   NaN   NaN   NaN        322.0
6    NaN   NaN   NaN   NaN   NaN   NaN        351.0
7    NaN   NaN   NaN   NaN   NaN   NaN        388.0
8    NaN   NaN   NaN   NaN   NaN   NaN        412.0
9    NaN   NaN   NaN   NaN   NaN   NaN        462.0
10   NaN   NaN   NaN   NaN   NaN   NaN       3189.0


In [33]:
print(df.median())

JAN             65.0
FEB             54.0
MAR             50.0
APR             59.0
MAY             56.0
JUN             55.0
TOTAL SALES    322.0
dtype: float64


In [34]:
print(df.describe())

              JAN         FEB         MAR         APR         MAY         JUN  \
count   11.000000   11.000000   11.000000   11.000000   11.000000   11.000000   
mean   101.090909   98.909091   94.909091  103.818182   96.727273   85.090909   
std    152.263886  148.884153  142.770763  155.277054  145.500578  128.347540   
min     29.000000   25.000000   15.000000   45.000000   25.000000   25.000000   
25%     35.000000   40.000000   47.000000   49.000000   40.000000   30.000000   
50%     65.000000   54.000000   50.000000   59.000000   56.000000   55.000000   
75%     76.000000   75.500000   71.500000   66.500000   69.500000   69.000000   
max    556.000000  544.000000  522.000000  571.000000  532.000000  468.000000   

       TOTAL SALES  
count    11.000000  
mean    579.818182  
std     869.142775  
min     210.000000  
25%     252.500000  
50%     322.000000  
75%     400.000000  
max    3189.000000  


In [35]:
print(df.sum())

JAN            1112.0
FEB            1088.0
MAR            1044.0
APR            1142.0
MAY            1064.0
JUN             936.0
TOTAL SALES    6378.0
dtype: float64


In [36]:
print(df.cumsum())

       JAN     FEB     MAR     APR     MAY    JUN  TOTAL SALES
0     70.0    80.0    75.0    60.0    72.0   55.0        412.0
1    100.0   128.0   110.0   105.0    97.0   92.0        632.0
2    165.0   182.0   159.0   159.0   132.0  157.0        954.0
3    250.0   253.0   227.0   236.0   220.0  230.0       1416.0
4    305.0   278.0   272.0   286.0   273.0  260.0       1674.0
5    340.0   323.0   287.0   331.0   318.0  285.0       1884.0
6    415.0   389.0   346.0   396.0   374.0  315.0       2235.0
7    444.0   424.0   395.0   444.0   409.0  370.0       2482.0
8    479.0   459.0   445.0   503.0   476.0  443.0       2801.0
9    556.0   544.0   522.0   571.0   532.0  468.0       3189.0
10  1112.0  1088.0  1044.0  1142.0  1064.0  936.0          NaN
11     NaN     NaN     NaN     NaN     NaN    NaN       6378.0


In [37]:
print(df.min())

JAN             29.0
FEB             25.0
MAR             15.0
APR             45.0
MAY             25.0
JUN             25.0
TOTAL SALES    210.0
dtype: float64


In [38]:
print(df.max())

JAN             556.0
FEB             544.0
MAR             522.0
APR             571.0
MAY             532.0
JUN             468.0
TOTAL SALES    3189.0
dtype: float64


In [39]:
print(df.count())

JAN            11
FEB            11
MAR            11
APR            11
MAY            11
JUN            11
TOTAL SALES    11
dtype: int64


In [40]:
from numpy import cov
covariance=cov(df)
print(covariance)

[[16913.57142857  8990.95238095 13122.66666667 18879.5
  10541.07142857  8595.         14418.92857143 10012.04761905
  12950.88095238 15993.61904762            nan            nan]
 [ 8990.95238095  4865.14285714  7054.5        10044.
   5572.61904762  4601.66666667  7668.71428571  5395.35714286
   6931.35714286  8508.80952381            nan            nan]
 [13122.66666667  7054.5        10390.66666667 14738.33333333
   8206.5         6675.         11198.          7881.
  10152.16666667 12361.5                   nan            nan]
 [18879.5        10044.         14738.33333333 21228.
  11883.          9670.         16115.66666667 11241.83333333
  14631.66666667 17771.5                   nan            nan]
 [10541.07142857  5572.61904762  8206.5        11883.
   6735.23809524  5388.33333333  9059.76190476  6266.04761905
   8168.88095238  9974.11904762            nan            nan]
 [ 8595.          4601.66666667  6675.          9670.
   5388.33333333  4508.33333333  7377.5         50

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   JAN          11 non-null     float64
 1   FEB          11 non-null     float64
 2   MAR          11 non-null     float64
 3   APR          11 non-null     float64
 4   MAY          11 non-null     float64
 5   JUN          11 non-null     float64
 6   TOTAL SALES  11 non-null     float64
dtypes: float64(7)
memory usage: 804.0 bytes


#DATASET 3

In [45]:
df=pd.read_csv(r"C:\Users\SCET\Downloads\4_Drug200.csv")

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    object 
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    object 
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB


In [48]:
df=df[["Age","Na_to_K"]]

In [50]:
print(df.describe())

              Age     Na_to_K
count  200.000000  200.000000
mean    44.315000   16.084485
std     16.544315    7.223956
min     15.000000    6.269000
25%     31.000000   10.445500
50%     45.000000   13.936500
75%     58.000000   19.380000
max     74.000000   38.247000


In [51]:
print(df.mean())

Age        44.315000
Na_to_K    16.084485
dtype: float64


In [52]:
print(df.median())

Age        45.0000
Na_to_K    13.9365
dtype: float64


In [54]:
print(df.mode())

    Age  Na_to_K
0  47.0   12.006
1   NaN   18.295


In [55]:
print(df.sum())

Age        8863.000
Na_to_K    3216.897
dtype: float64


In [56]:
print(df.cumsum())

      Age   Na_to_K
0      23    25.355
1      70    38.448
2     117    48.562
3     145    56.360
4     206    74.403
..    ...       ...
195  8732  3169.628
196  8748  3181.634
197  8800  3191.528
198  8823  3205.548
199  8863  3216.897

[200 rows x 2 columns]


In [57]:
print(df.min())

Age        15.000
Na_to_K     6.269
dtype: float64


In [58]:
print(df.max())

Age        74.000
Na_to_K    38.247
dtype: float64


In [59]:
print(df.count())

Age        200
Na_to_K    200
dtype: int64


In [60]:
from numpy import cov
covariance=cov(df)
print(covariance)

[[  2.7730125 -39.9254925 -43.433265  ... -49.579815  -10.57395
  -33.7365525]
 [-39.9254925 574.8423245 625.346801  ... 713.844071  152.24243
  485.7347285]
 [-43.433265  625.346801  680.288498  ... 776.560958  165.61814
  528.410393 ]
 ...
 [-49.579815  713.844071  776.560958  ... 886.457618  189.05594
  603.189503 ]
 [-10.57395   152.24243   165.61814   ... 189.05594    40.3202
  128.64299  ]
 [-33.7365525 485.7347285 528.410393  ... 603.189503  128.64299
  410.4399005]]


In [61]:
from scipy.stats import pearsonr#it works well for linear relationship/regression
corr,_=pearsonr(df['Age'],df['Na_to_K'])
print(corr)

-0.0631194972677259
